### ISSUE TITLE
Latest npm package is missing the library

### ISSUE THREAD

**Issue by sylv** [loweisz/generate-avatar#11]
The latest npm package is missing the library entirely, no source or compiled files are included. Honestly still not sure if I'm just being an idiot but downloading the latest version from https://registry.npmjs.org/generate-avatar/-/generate-avatar-1.4.9.tgz it looks like it is just missing the library entirely.

**Comment by loweisz** [comment]
@sylv Fair point, it looks like I forgot to build the package before publishing it. My apologies, the new version should contain the build again. 
https://www.npmjs.com/package/generate-avatar

Thanks for catching it 🙏
